//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeployCmdlets4WA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeployCmdlets4WA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://windows.azure.com/download/publishprofile.aspx?client=nodejs&amp;lang=en.
        /// </summary>
        internal static string AzureIaaSPublishSettingsURL {
            get {
                return ResourceManager.GetString("AzureIaaSPublishSettingsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://windows.azure.com/download/publishprofile.aspx?client=nodejs&amp;lang=en.
        /// </summary>
        internal static string AzurePaaSPublishSettingsURL {
            get {
                return ResourceManager.GetString("AzurePaaSPublishSettingsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceConfiguration.Cloud.cscfg.
        /// </summary>
        internal static string CSCFGCloudFile {
            get {
                return ResourceManager.GetString("CSCFGCloudFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSCFG file does not exist..
        /// </summary>
        internal static string CSCFGFileDoesNotExist {
            get {
                return ResourceManager.GetString("CSCFGFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceConfiguration.Local.cscfg.
        /// </summary>
        internal static string CSCFGLocalFile {
            get {
                return ResourceManager.GetString("CSCFGLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDefinition.csdef.
        /// </summary>
        internal static string CSDEFFile {
            get {
                return ResourceManager.GetString("CSDEFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSDEF file does not exist..
        /// </summary>
        internal static string CSDEFFileDoesNotExist {
            get {
                return ResourceManager.GetString("CSDEFFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataConnectionString.
        /// </summary>
        internal static string DataConnectionString {
            get {
                return ResourceManager.GetString("DataConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.WindowsAzure.Plugins.Diagnostics.ConnectionString.
        /// </summary>
        internal static string DiagnosticsConnectionString {
            get {
                return ResourceManager.GetString("DiagnosticsConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point config missing for &apos;{0}&apos; inside CSDEF..
        /// </summary>
        internal static string EntryPointConfigMissing {
            get {
                return ResourceManager.GetString("EntryPointConfigMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvokeExecutable execution failed unable to locate check file &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorExecutingExecutable {
            get {
                return ResourceManager.GetString("ErrorExecutingExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing &apos;{0}&apos; module(s)..
        /// </summary>
        internal static string ErrorInstallingModules {
            get {
                return ResourceManager.GetString("ErrorInstallingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Endpoints for &apos;{0}&apos; service..
        /// </summary>
        internal static string FetchingEndpoints {
            get {
                return ResourceManager.GetString("FetchingEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL not in correct format..
        /// </summary>
        internal static string IncorrectURL {
            get {
                return ResourceManager.GetString("IncorrectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find setup file at download location..
        /// </summary>
        internal static string InvalidDownloadLocMessage {
            get {
                return ResourceManager.GetString("InvalidDownloadLocMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location specified inside &apos;{0}&apos; param does not exist..
        /// </summary>
        internal static string InvalidInstallLoc {
            get {
                return ResourceManager.GetString("InvalidInstallLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role binary folder does not exist..
        /// </summary>
        internal static string InvalidRoleBinaryFolder {
            get {
                return ResourceManager.GetString("InvalidRoleBinaryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account names must be between 3 and 24 characters in length and use numbers and letters only..
        /// </summary>
        internal static string InvalidStorageAccountNameMessage {
            get {
                return ResourceManager.GetString("InvalidStorageAccountNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XmlConfigPath..
        /// </summary>
        internal static string InvalidXmlConfigPath {
            get {
                return ResourceManager.GetString("InvalidXmlConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; already present in the CSCFG. Instance count is {1}..
        /// </summary>
        internal static string RoleAlreadyPresentInCSCFG {
            get {
                return ResourceManager.GetString("RoleAlreadyPresentInCSCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; already present in the CSDEF. VMSize is {1}..
        /// </summary>
        internal static string RoleAlreadyPresentInCSDEF {
            get {
                return ResourceManager.GetString("RoleAlreadyPresentInCSDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; for role binaries already exists. Hence no changes made to binaries..
        /// </summary>
        internal static string RoleDirAlreadyPresent {
            get {
                return ResourceManager.GetString("RoleDirAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with &apos;{0}&apos; rolename not found in CSCFG file..
        /// </summary>
        internal static string RoleNotFoundInCSCFG {
            get {
                return ResourceManager.GetString("RoleNotFoundInCSCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with &apos;{0}&apos; rolename not found in CSDEF file..
        /// </summary>
        internal static string RoleNotFoundInCSDEF {
            get {
                return ResourceManager.GetString("RoleNotFoundInCSDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate CSCFG or CSDEF file in service root directory. Execute New-AzureServiceProject command..
        /// </summary>
        internal static string ServiceRootInvalid {
            get {
                return ResourceManager.GetString("ServiceRootInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; already exists..
        /// </summary>
        internal static string StorageAccAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("StorageAccAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure storage account configured..
        /// </summary>
        internal static string StorageAccConfigSuccess {
            get {
                return ResourceManager.GetString("StorageAccConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; created..
        /// </summary>
        internal static string StorageAccCreatedMessage {
            get {
                return ResourceManager.GetString("StorageAccCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account creation failed with status {0}..
        /// </summary>
        internal static string StorageAccCreationFailed {
            get {
                return ResourceManager.GetString("StorageAccCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already created the maximum number of storage accounts..
        /// </summary>
        internal static string StorageAccLimitReached {
            get {
                return ResourceManager.GetString("StorageAccLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription &apos;{0}&apos; not found in publishSettings file..
        /// </summary>
        internal static string SubscriptionNotFound {
            get {
                return ResourceManager.GetString("SubscriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip location does not exist..
        /// </summary>
        internal static string UnzipLocDoesNotExist {
            get {
                return ResourceManager.GetString("UnzipLocDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification failed with error &quot;{0}&quot;..
        /// </summary>
        internal static string VerificationFailedNoRetry {
            get {
                return ResourceManager.GetString("VerificationFailedNoRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification failed. System shall retry after some time..
        /// </summary>
        internal static string VerificationFailedRetry {
            get {
                return ResourceManager.GetString("VerificationFailedRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification successful..
        /// </summary>
        internal static string VerificationSuccess {
            get {
                return ResourceManager.GetString("VerificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying Endpoint &apos;{0}:{1}&apos;..
        /// </summary>
        internal static string VerifyingEndpoint {
            get {
                return ResourceManager.GetString("VerifyingEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying if Storage account count exceeded..
        /// </summary>
        internal static string VerifyStorageAccCount {
            get {
                return ResourceManager.GetString("VerifyStorageAccCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://go.microsoft.com/fwlink/?LinkId=233753.
        /// </summary>
        internal static string WebPICmdlineURL {
            get {
                return ResourceManager.GetString("WebPICmdlineURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows service &apos;{0}&apos; is already stopped..
        /// </summary>
        internal static string WinServiceAlreadyStopped {
            get {
                return ResourceManager.GetString("WinServiceAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows service &apos;{0}&apos; stopped successfully..
        /// </summary>
        internal static string WinServiceStopped {
            get {
                return ResourceManager.GetString("WinServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to stop the service..
        /// </summary>
        internal static string WinServiceStopping {
            get {
                return ResourceManager.GetString("WinServiceStopping", resourceCulture);
            }
        }
    }
}
