//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeployCmdlets4WA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeployCmdlets4WA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure disk &apos;{0}&apos; deleted..
        /// </summary>
        internal static string AzureDiskDeleted {
            get {
                return ResourceManager.GetString("AzureDiskDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://windows.azure.com/download/publishprofile.aspx?client=nodejs&amp;lang=en.
        /// </summary>
        internal static string AzureIaaSPublishSettingsURL {
            get {
                return ResourceManager.GetString("AzureIaaSPublishSettingsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://manage.windowsazure.cn/publishsettings/index.
        /// </summary>
        internal static string AzureIaaSPublishSettingsURLCN {
            get {
                return ResourceManager.GetString("AzureIaaSPublishSettingsURLCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://windows.azure.com/download/publishprofile.aspx?client=nodejs&amp;lang=en.
        /// </summary>
        internal static string AzurePaaSPublishSettingsURL {
            get {
                return ResourceManager.GetString("AzurePaaSPublishSettingsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://manage.windowsazure.cn/publishsettings/index.
        /// </summary>
        internal static string AzurePaaSPublishSettingsURLCN {
            get {
                return ResourceManager.GetString("AzurePaaSPublishSettingsURLCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {{
        ///        &quot;SSH&quot;: [
        ///            {{
        ///                &quot;info&quot;: {{
        ///                    &quot;host&quot;: &quot;{0}&quot;,
        ///                    &quot;user&quot;: &quot;{1}&quot;,
        ///                    &quot;password&quot;: &quot;{2}&quot;,
        ///                    &quot;ports&quot;: [
        ///                        {3}
        ///                    ]
        ///                }}
        ///            }}
        ///        ]
        ///    }},
        ///    {{
        ///        &quot;VMS&quot;: [
        ///           {{
        ///                &quot;info&quot;: {{
        ///                    &quot;ips&quot;: [
        ///                        {4}
        ///                    ]
        ///                }}
        ///            }}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigJson {
            get {
                return ResourceManager.GetString("ConfigJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring WinRM Auth..
        /// </summary>
        internal static string ConfigWinRMAuth {
            get {
                return ResourceManager.GetString("ConfigWinRMAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring WinRM Encrypt..
        /// </summary>
        internal static string ConfigWinRMEnc {
            get {
                return ResourceManager.GetString("ConfigWinRMEnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring WinRM trusted host..
        /// </summary>
        internal static string ConfigWinRMTrustedHost {
            get {
                return ResourceManager.GetString("ConfigWinRMTrustedHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying VHD from &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string CopyingVHD {
            get {
                return ResourceManager.GetString("CopyingVHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating container &apos;{0}&apos; if it does not exist..
        /// </summary>
        internal static string CreatingContainerIfNotExists {
            get {
                return ResourceManager.GetString("CreatingContainerIfNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating service &apos;{0}&apos;..
        /// </summary>
        internal static string CreatingService {
            get {
                return ResourceManager.GetString("CreatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating VM image &apos;{0}&apos;..
        /// </summary>
        internal static string CreatingVMImage {
            get {
                return ResourceManager.GetString("CreatingVMImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceConfiguration.Cloud.cscfg.
        /// </summary>
        internal static string CSCFGCloudFile {
            get {
                return ResourceManager.GetString("CSCFGCloudFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSCFG file does not exist..
        /// </summary>
        internal static string CSCFGFileDoesNotExist {
            get {
                return ResourceManager.GetString("CSCFGFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceConfiguration.Local.cscfg.
        /// </summary>
        internal static string CSCFGLocalFile {
            get {
                return ResourceManager.GetString("CSCFGLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceDefinition.csdef.
        /// </summary>
        internal static string CSDEFFile {
            get {
                return ResourceManager.GetString("CSDEFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSDEF file does not exist..
        /// </summary>
        internal static string CSDEFFileDoesNotExist {
            get {
                return ResourceManager.GetString("CSDEFFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataConnectionString.
        /// </summary>
        internal static string DataConnectionString {
            get {
                return ResourceManager.GetString("DataConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Azure disk &apos;{0}&apos;..
        /// </summary>
        internal static string DeletingAzureDisk {
            get {
                return ResourceManager.GetString("DeletingAzureDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting VM &apos;{0}&apos;..
        /// </summary>
        internal static string DeletingVM {
            get {
                return ResourceManager.GetString("DeletingVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.WindowsAzure.Plugins.Diagnostics.ConnectionString.
        /// </summary>
        internal static string DiagnosticsConnectionString {
            get {
                return ResourceManager.GetString("DiagnosticsConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling WinRM service on your machine..
        /// </summary>
        internal static string EnablingWinRM {
            get {
                return ResourceManager.GetString("EnablingWinRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point config missing for &apos;{0}&apos; inside the CSDEF file..
        /// </summary>
        internal static string EntryPointConfigMissing {
            get {
                return ResourceManager.GetString("EntryPointConfigMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting WinRM config..
        /// </summary>
        internal static string ErrorConfigWinRM {
            get {
                return ResourceManager.GetString("ErrorConfigWinRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating new service with name &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorCreatingService {
            get {
                return ResourceManager.GetString("ErrorCreatingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erorr deleting Azure disk &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorDeletingAzureDisk {
            get {
                return ResourceManager.GetString("ErrorDeletingAzureDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting VM &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorDeletingVM {
            get {
                return ResourceManager.GetString("ErrorDeletingVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while enabling WinRM on local machine..
        /// </summary>
        internal static string ErrorEnablingWinRM {
            get {
                return ResourceManager.GetString("ErrorEnablingWinRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvokeExecutable execution failed: unable to locate check file &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorExecutingExecutable {
            get {
                return ResourceManager.GetString("ErrorExecutingExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching list of existing VMs in service &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorFetchingExistingVMs {
            get {
                return ResourceManager.GetString("ErrorFetchingExistingVMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error fetching OS disk details for VM &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorFetchingOSDiskForVM {
            get {
                return ResourceManager.GetString("ErrorFetchingOSDiskForVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing &apos;{0}&apos; module(s)..
        /// </summary>
        internal static string ErrorInstallingModules {
            get {
                return ResourceManager.GetString("ErrorInstallingModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error installing WebPI. Unable to locate WebPICmdline.exe at &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorInstallingWebPI {
            get {
                return ResourceManager.GetString("ErrorInstallingWebPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting default storage account..
        /// </summary>
        internal static string ErrorSettingDefaultStorageAcc {
            get {
                return ResourceManager.GetString("ErrorSettingDefaultStorageAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error verifying if service exists..
        /// </summary>
        internal static string ErrorVerifyingIfServiceExist {
            get {
                return ResourceManager.GetString("ErrorVerifyingIfServiceExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while trying check if the VM image already exists..
        /// </summary>
        internal static string ErrorVerifyingVMImageExists {
            get {
                return ResourceManager.GetString("ErrorVerifyingVMImageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Get-AzureVMImage..
        /// </summary>
        internal static string ExecutingGetAzureVMImage {
            get {
                return ResourceManager.GetString("ExecutingGetAzureVMImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching OS disk details for VM &apos;{0}&apos;..
        /// </summary>
        internal static string FetchigOSDiskForVM {
            get {
                return ResourceManager.GetString("FetchigOSDiskForVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Endpoints for &apos;{0}&apos; service..
        /// </summary>
        internal static string FetchingEndpoints {
            get {
                return ResourceManager.GetString("FetchingEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching existing VMs in service &apos;{0}&apos;..
        /// </summary>
        internal static string FetchingExistingVMs {
            get {
                return ResourceManager.GetString("FetchingExistingVMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching storage account keys for &apos;{0}&apos;..
        /// </summary>
        internal static string FetchingStorageAccKeys {
            get {
                return ResourceManager.GetString("FetchingStorageAccKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for the Force parameter. Correct values are True or False..
        /// </summary>
        internal static string ForceParamInvalid {
            get {
                return ResourceManager.GetString("ForceParamInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get-AzureVMImage failed..
        /// </summary>
        internal static string GetAzureVMImageFailed {
            get {
                return ResourceManager.GetString("GetAzureVMImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VHD ImageUrl for location &apos;{0}&apos; not found..
        /// </summary>
        internal static string ImgUrlNotFoundForLocation {
            get {
                return ResourceManager.GetString("ImgUrlNotFoundForLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified URL is not formatted correctly..
        /// </summary>
        internal static string IncorrectURL {
            get {
                return ResourceManager.GetString("IncorrectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find setup file at the download location..
        /// </summary>
        internal static string InvalidDownloadLocMessage {
            get {
                return ResourceManager.GetString("InvalidDownloadLocMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location specified inside &apos;{0}&apos; param does not exist..
        /// </summary>
        internal static string InvalidInstallLoc {
            get {
                return ResourceManager.GetString("InvalidInstallLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role binary folder does not exist..
        /// </summary>
        internal static string InvalidRoleBinaryFolder {
            get {
                return ResourceManager.GetString("InvalidRoleBinaryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for Settings. Setting should be provided in SettingName:SettingValue format separated by comma. .
        /// </summary>
        internal static string InvalidSettings {
            get {
                return ResourceManager.GetString("InvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account names must be between 3 and 24 characters in length and use numbers and letters only..
        /// </summary>
        internal static string InvalidStorageAccountNameMessage {
            get {
                return ResourceManager.GetString("InvalidStorageAccountNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM name &apos;{0}&apos; is invalid. The VM name may not be more than 15 characters long, may not be entirely numeric, and may not contain the following characters: ~ ! @ # $ % ^ &amp; * ( ) = + _ [ ] {{}} \ | ; : . &apos; &quot; , &lt; / ?..
        /// </summary>
        internal static string InvalidVMName {
            get {
                return ResourceManager.GetString("InvalidVMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XmlConfigPath..
        /// </summary>
        internal static string InvalidXmlConfigPath {
            get {
                return ResourceManager.GetString("InvalidXmlConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string LocationXmlNotFound {
            get {
                return ResourceManager.GetString("LocationXmlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription you have specified is not meant for targeting the Windows Azure environment you have specified. Please check your subscription and the ServiceEnvironment parameter in your configuration XML file..
        /// </summary>
        internal static string MgmtUrlMismatch {
            get {
                return ResourceManager.GetString("MgmtUrlMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Disk name for VM &apos;{0}&apos; is &apos;{1}&apos;..
        /// </summary>
        internal static string OSDiskNameForVM {
            get {
                return ResourceManager.GetString("OSDiskNameForVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powershell 3.0 is required. Please follow the instructions on http://technet.microsoft.com/en-us/library/hh847837.aspx to install Powershell 3.0.
        /// </summary>
        internal static string PowersehllV3Required {
            get {
                return ResourceManager.GetString("PowersehllV3Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; is already present in the CSCFG. Instance count is {1}..
        /// </summary>
        internal static string RoleAlreadyPresentInCSCFG {
            get {
                return ResourceManager.GetString("RoleAlreadyPresentInCSCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role &apos;{0}&apos; is already present in the CSDEF. VMSize is {1}..
        /// </summary>
        internal static string RoleAlreadyPresentInCSDEF {
            get {
                return ResourceManager.GetString("RoleAlreadyPresentInCSDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; for role binaries already exists. Hence no changes were made to the binaries..
        /// </summary>
        internal static string RoleDirAlreadyPresent {
            get {
                return ResourceManager.GetString("RoleDirAlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with role name &apos;{0}&apos; was not found in the CSCFG file..
        /// </summary>
        internal static string RoleNotFoundInCSCFG {
            get {
                return ResourceManager.GetString("RoleNotFoundInCSCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with the role name &apos;{0}&apos; was not found in the CSDEF file..
        /// </summary>
        internal static string RoleNotFoundInCSDEF {
            get {
                return ResourceManager.GetString("RoleNotFoundInCSDEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service with name &apos;{0}&apos; already exists. Hence VM&apos;s shall be added to same service..
        /// </summary>
        internal static string ServiceExists {
            get {
                return ResourceManager.GetString("ServiceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot locate CSCFG or CSDEF file in service root directory. Execute New-AzureServiceProject command..
        /// </summary>
        internal static string ServiceRootInvalid {
            get {
                return ResourceManager.GetString("ServiceRootInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting &apos;{0}&apos; as default storage acocunt for subscription &apos;{1}&apos;..
        /// </summary>
        internal static string SetDefaultStorageAcc {
            get {
                return ResourceManager.GetString("SetDefaultStorageAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting &apos;{0}&apos; absent in CscfgFile..
        /// </summary>
        internal static string SettingAbsentInCSCFG {
            get {
                return ResourceManager.GetString("SettingAbsentInCSCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CscfgFile does not have any settings..
        /// </summary>
        internal static string SettingsAbsentInCSCFG {
            get {
                return ResourceManager.GetString("SettingsAbsentInCSCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; already exists..
        /// </summary>
        internal static string StorageAccAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("StorageAccAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure storage account configured..
        /// </summary>
        internal static string StorageAccConfigSuccess {
            get {
                return ResourceManager.GetString("StorageAccConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; created..
        /// </summary>
        internal static string StorageAccCreatedMessage {
            get {
                return ResourceManager.GetString("StorageAccCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account creation failed with status {0}..
        /// </summary>
        internal static string StorageAccCreationFailed {
            get {
                return ResourceManager.GetString("StorageAccCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values you have specified for the Location and StorageAccount parameters will result in your service and storage account being created in a different geographical regions, resulting in lower performance and higher costs for you. Please consider adjusting the values.
        /// </summary>
        internal static string StorageAccDiffLocationWarning {
            get {
                return ResourceManager.GetString("StorageAccDiffLocationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage account &apos;{0}&apos; does not belong to the given subscription..
        /// </summary>
        internal static string StorageAccExistsForDiffSubscription {
            get {
                return ResourceManager.GetString("StorageAccExistsForDiffSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already created the maximum number of storage accounts..
        /// </summary>
        internal static string StorageAccLimitReached {
            get {
                return ResourceManager.GetString("StorageAccLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription &apos;{0}&apos; not found in publishSettings file..
        /// </summary>
        internal static string SubscriptionNotFound {
            get {
                return ResourceManager.GetString("SubscriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unzip location does not exist..
        /// </summary>
        internal static string UnzipLocDoesNotExist {
            get {
                return ResourceManager.GetString("UnzipLocDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the Remote UAC LocalAccountTokenFilterPolicy registry setting..
        /// </summary>
        internal static string UpdateRegistryForWinRM {
            get {
                return ResourceManager.GetString("UpdateRegistryForWinRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification failed with error &quot;{0}&quot;..
        /// </summary>
        internal static string VerificationFailedNoRetry {
            get {
                return ResourceManager.GetString("VerificationFailedNoRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification failed. The installer will retry after some time..
        /// </summary>
        internal static string VerificationFailedRetry {
            get {
                return ResourceManager.GetString("VerificationFailedRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification successful..
        /// </summary>
        internal static string VerificationSuccess {
            get {
                return ResourceManager.GetString("VerificationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying if service with name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string VerifyIfServiceExist {
            get {
                return ResourceManager.GetString("VerifyIfServiceExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying Endpoint &apos;{0}:{1}&apos;..
        /// </summary>
        internal static string VerifyingEndpoint {
            get {
                return ResourceManager.GetString("VerifyingEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if VM image &quot;{0}&quot; already exists..
        /// </summary>
        internal static string VerifyingVMImageExists {
            get {
                return ResourceManager.GetString("VerifyingVMImageExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying if WebPI installation..
        /// </summary>
        internal static string VerifyingWebPIInstallation {
            get {
                return ResourceManager.GetString("VerifyingWebPIInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifying if Storage account count exceeded..
        /// </summary>
        internal static string VerifyStorageAccCount {
            get {
                return ResourceManager.GetString("VerifyStorageAccCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM &apos;{0}&apos; already exists..
        /// </summary>
        internal static string VMAlreadyExists {
            get {
                return ResourceManager.GetString("VMAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM count should be greater than zero..
        /// </summary>
        internal static string VMCountInvalid {
            get {
                return ResourceManager.GetString("VMCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM &apos;{0}&apos; deleted..
        /// </summary>
        internal static string VMDeletionSuccess {
            get {
                return ResourceManager.GetString("VMDeletionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to create a WinRM-enabled Windows image failed..
        /// </summary>
        internal static string VMImageCreationFailed {
            get {
                return ResourceManager.GetString("VMImageCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM image for the &apos;{0}&apos; family was not found in the current Azure environment..
        /// </summary>
        internal static string VMImageNotFoundFmt {
            get {
                return ResourceManager.GetString("VMImageNotFoundFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM image properties:.
        /// </summary>
        internal static string VMImagePropHeader {
            get {
                return ResourceManager.GetString("VMImagePropHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating VM &apos;{0}&apos;. The installer will retry after &apos;{1}&apos; seconds..
        /// </summary>
        internal static string WarnAzureVMCreationFailed {
            get {
                return ResourceManager.GetString("WarnAzureVMCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting VM &apos;{0}&apos;. The installer will retry after &apos;{1}&apos; seconds..
        /// </summary>
        internal static string WarnAzureVMDeleteError {
            get {
                return ResourceManager.GetString("WarnAzureVMDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erorr deleting Azure disk &apos;{0}&apos;.System will retry after &apos;{1}&apos; seconds..
        /// </summary>
        internal static string WarnErrorDeletingAzureDisk {
            get {
                return ResourceManager.GetString("WarnErrorDeletingAzureDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://download.microsoft.com/download/7/0/4/704CEB4C-9F42-4962-A2B0-5C84B0682C7A/WebPlatformInstaller_amd64_en-US.msi.
        /// </summary>
        internal static string WebPIDownloadLoc {
            get {
                return ResourceManager.GetString("WebPIDownloadLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Server 2008 R2 SP1.
        /// </summary>
        internal static string Win2KR8SP1FamilyName {
            get {
                return ResourceManager.GetString("Win2KR8SP1FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows service &apos;{0}&apos; is already stopped..
        /// </summary>
        internal static string WinServiceAlreadyStopped {
            get {
                return ResourceManager.GetString("WinServiceAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows service &apos;{0}&apos; stopped successfully..
        /// </summary>
        internal static string WinServiceStopped {
            get {
                return ResourceManager.GetString("WinServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to stop the service..
        /// </summary>
        internal static string WinServiceStopping {
            get {
                return ResourceManager.GetString("WinServiceStopping", resourceCulture);
            }
        }
    }
}
