using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Diagnostics.CodeAnalysis;

[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.ServiceProxy.Deployment.#RoleList")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.ServiceProxy.HostedService.#Deployments")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.ServiceProxy.NetworkConfigurationSet.#InputEndpoints")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.ServiceProxy.Role.#ConfigurationSets")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.Destinations.#RoleEndpoint")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.VirtualDirectory.#ItemsElementName")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.VirtualDirectory.#Items")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.VirtualMachineRoleLocalResources.#LocalStorage")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.InternalEndpoint.#FixedPort")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.InternalEndpoint.#FixedPortRange")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.Endpoints.#InputEndpoint")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.Endpoints.#InternalEndpoint")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WorkerRole.#ConfigurationSettings")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WorkerRole.#Certificates")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WorkerRole.#Contents")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WorkerRole.#Imports")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.Task.#Environment")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.Sites.#Site")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.Runtime.#Environment")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.ServiceDefinition.#WorkerRole")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.ServiceDefinition.#NetworkTrafficRules")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.ServiceDefinition.#VirtualMachineRole")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.ServiceDefinition.#WebRole")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WebRole.#Certificates")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WebRole.#Contents")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WebRole.#Imports")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WebRole.#ConfigurationSettings")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WebRoleInputEndpoints.#InputEndpoint")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.WhenSource.#FromRole")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.VirtualMachineRole.#ConfigurationSettings")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.VirtualMachineRole.#Certificates")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.VirtualMachineRole.#Imports")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.RoleModule.#ConfigurationSettings")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.RoleModule.#Certificates")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.LocalResources.#LocalStorage")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.Startup.#Task")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceDefinitionSchema.Site.#Bindings")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceConfigurationSchema.ServiceConfiguration.#Role")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceConfigurationSchema.RoleSettings.#ConfigurationSettings")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeployCmdlets4WA.Cmdlet.ServiceConfigurationSchema.RoleSettings.#Certificates")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeploymentModelStepsStep.#CommandParam")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeploymentModel.#Items")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeploymentModelSteps.#Step")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "DeploymentModelParameters.#Parameter")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Microsoft.WindowsAzure.Management.XmlSchema.PublishData.#Items")]
[module: SuppressMessage("Microsoft.Performance", "CA1819:PropertiesShouldNotReturnArrays", Scope = "member", Target = "Microsoft.WindowsAzure.Management.XmlSchema.PublishDataPublishProfile.#Subscription")]
